import os

TEST_USERDB_URL = os.getenv('TEST_USERDB_IP')
TEST_USERDB_PORT = os.getenv('TEST_USERDB_PORT')
TEST_USERDB_NAME = os.getenv('TEST_USERDB_NAME')
TEST_USERDB_USERNAME = os.getenv('TEST_USERDB_USERNAME')
TEST_USERDB_PASSWORD = os.getenv('TEST_USERDB_PASSWORD')
